#!/usr/bin/env python3
"""Plugin marketplace manager for Kilo Code (and Claude Code).

Emulates Claude Code's native plugin-marketplace mechanism for tools that
lack it. A "marketplace" is any git repo laid out in Claude Code's plugin
format (`.claude-plugin/marketplace.json` + plugin dirs with `skills/`,
`agents/`, `commands/`), so the SAME repo serves Claude Code users natively
and Kilo/other users through this script.

Subcommands:
  add <git-url-or-path> [--name N]   clone/refresh a marketplace under ~/.kilo/marketplaces/
  remove <marketplace>               drop a marketplace checkout (warns about live installs)
  list                               show available plugins with installed state/version
  install <plugin>[@marketplace]     symlink skills, generate agents/commands
          [--project PATH] [--copy] [--no-claude]
  uninstall <plugin>[@marketplace] [--project PATH]
  update [marketplace]               git pull marketplaces + refresh every recorded install
  status                             marketplaces, HEAD commits, recorded installs
  convert <file.md> --to kilo|claude [-o OUT]   translate one agent file's frontmatter
  init-marketplace <path> [--name N] scaffold a new marketplace repo

State lives in ~/.kilo/plugin-manager.json. Only paths recorded there are
ever overwritten or removed; anything else is warned about and left alone.
Set KILO_PM_ROOT to relocate ~ for testing.
"""
import argparse
import hashlib
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys

ROOT = pathlib.Path(os.environ.get('KILO_PM_ROOT', str(pathlib.Path.home())))
KILO_HOME = ROOT / '.kilo'
CLAUDE_HOME = ROOT / '.claude'
MARKETPLACES_DIR = KILO_HOME / 'marketplaces'
STATE_PATH = KILO_HOME / 'plugin-manager.json'

FRONTMATTER_RE = re.compile(r'^---\n(.*?)\n---\n?(.*)$', re.DOTALL)

# Claude tool name (lowercased) -> Kilo permission key
TOOL_PERMISSION_MAP = {
    'read': 'read', 'grep': 'read', 'glob': 'read',
    'edit': 'edit', 'write': 'edit', 'notebookedit': 'edit',
    'bash': 'bash',
    'webfetch': 'webfetch', 'websearch': 'webfetch',
    'skill': 'skill',
}
# Kilo permission key -> Claude tool names
PERMISSION_TOOL_MAP = {
    'read': ['Read', 'Grep', 'Glob'],
    'edit': ['Edit', 'Write'],
    'bash': ['Bash'],
    'webfetch': ['WebFetch', 'WebSearch'],
    'skill': ['Skill'],
}
KILO_PERMISSION_ORDER = ['read', 'edit', 'bash', 'skill', 'webfetch', 'mcp']
DEFAULT_KILO_PERMISSIONS = ['read', 'edit', 'bash', 'skill', 'webfetch']
GENERATED_MARK = '# generated by kilo-plugin-manager — edit the plugin source, not this file'


def die(msg):
    print(f'error: {msg}', file=sys.stderr)
    sys.exit(1)


def run_git(args, cwd=None):
    r = subprocess.run(['git'] + args, cwd=cwd, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {r.stderr.strip()}")
    return r.stdout.strip()


def load_state():
    if STATE_PATH.exists():
        return json.loads(STATE_PATH.read_text())
    return {'marketplaces': {}, 'installs': {}}


def save_state(state):
    STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    STATE_PATH.write_text(json.dumps(state, indent=2) + '\n')


# ---------- frontmatter parsing / agent translation ----------

def parse_fm(text):
    """Flat-ish frontmatter parser: top-level `key: value` pairs; indented
    continuation lines (nested blocks like Kilo's `permission:`) are kept
    verbatim appended to their key's raw value."""
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, text
    fields, current = {}, None
    for line in m.group(1).split('\n'):
        if line.lstrip().startswith('#'):
            continue
        km = re.match(r'^([A-Za-z0-9_-]+)\s*:(.*)$', line)
        if km:
            current = km.group(1)
            fields[current] = km.group(2).strip()
        elif current is not None:
            fields[current] += '\n' + line
    return fields, m.group(2)


def is_kilo_shaped(fields):
    return 'mode' in fields or 'permission' in fields


def tools_to_permissions(tools_val):
    perms = set()
    for t in re.split(r'[,\s]+', tools_val):
        t = t.strip().lower()
        if not t:
            continue
        if t.startswith('mcp__') or t == 'mcp':
            perms.add('mcp')
        elif t in TOOL_PERMISSION_MAP:
            perms.add(TOOL_PERMISSION_MAP[t])
    return perms or set(DEFAULT_KILO_PERMISSIONS)


def sanitize_yaml_val(val):
    if not val:
        return '""'
    val = val.strip()
    # Kilo 7.4.5 YAML parser safety: no block scalars, no multiline, no internal double quotes
    if val.startswith('"') and val.endswith('"'):
        val = val[1:-1]
    elif val.startswith("'") and val.endswith("'"):
        val = val[1:-1]
    elif val.startswith('>'):
        val = val.lstrip('>-\n ')
    
    val = val.replace('\\"', '`').replace('"', '`')
    val = ' '.join(line.strip() for line in val.split('\n') if line.strip())
    
    return f'"{val}"'


def to_kilo_agent(name, fields, body, mark=True):
    if 'tools' in fields:
        perms = tools_to_permissions(fields['tools'])
    else:
        perms = set(DEFAULT_KILO_PERMISSIONS)
    desc = sanitize_yaml_val(fields.get('description', ''))
    lines = ['---']
    if mark:
        lines.append(GENERATED_MARK)
    lines += [f'name: {name}',
              f"description: {desc}",
              f"mode: {fields.get('mode', 'primary').split(chr(10))[0] or 'primary'}",
              'permission:']
    lines += [f'  {p}: allow' for p in KILO_PERMISSION_ORDER if p in perms]
    lines.append('---')
    return '\n'.join(lines) + '\n' + body


def to_claude_agent(name, fields, body, mark=True):
    perm_raw = fields.get('permission', '')
    tools = []
    if perm_raw:
        for key, names in PERMISSION_TOOL_MAP.items():
            if re.search(rf'\b{key}\s*:\s*allow', perm_raw):
                tools += names
    if not tools:
        tools = [t for names in PERMISSION_TOOL_MAP.values() for t in names]
    desc = sanitize_yaml_val(fields.get('description', ''))
    lines = ['---']
    if mark:
        lines.append(GENERATED_MARK)
    lines += [f'name: {name}',
              f"description: {desc}",
              f"tools: {', '.join(tools)}",
              '---']
    return '\n'.join(lines) + '\n' + body


def translate_agent(src_path, to):
    text = pathlib.Path(src_path).read_text()
    fields, body = parse_fm(text)
    name = fields.get('name', pathlib.Path(src_path).stem)
    if to == 'kilo':
        return text if is_kilo_shaped(fields) else to_kilo_agent(name, fields, body)
    return to_claude_agent(name, fields, body) if is_kilo_shaped(fields) else text


# ---------- marketplace discovery ----------

def marketplace_path(name):
    return MARKETPLACES_DIR / name


def marketplace_plugins(mp_path):
    """Return {plugin_name: {path, description, version}} for a marketplace
    checkout. Prefers .claude-plugin/marketplace.json; falls back to scanning
    plugins/ (or top-level) for dirs containing skills/agents/commands."""
    plugins = {}
    manifest = mp_path / '.claude-plugin' / 'marketplace.json'
    if manifest.exists():
        data = json.loads(manifest.read_text())
        for p in data.get('plugins', []):
            src = p.get('source', f"./plugins/{p['name']}")
            if not isinstance(src, str):
                continue  # external plugin sources not supported here
            plugins[p['name']] = {'path': (mp_path / src).resolve(),
                                  'description': p.get('description', '')}
    else:
        base = mp_path / 'plugins' if (mp_path / 'plugins').is_dir() else mp_path
        for d in sorted(base.iterdir()):
            if d.name.startswith('.') or not d.is_dir():
                continue
            if any((d / s).exists() for s in ('skills', 'agents', 'commands', '.claude-plugin')):
                plugins[d.name] = {'path': d, 'description': ''}
    for info in plugins.values():
        info.setdefault('version', None)
        pj = info['path'] / '.claude-plugin' / 'plugin.json'
        if pj.exists():
            try:
                pdata = json.loads(pj.read_text())
                info['version'] = pdata.get('version')
                info['description'] = info['description'] or pdata.get('description', '')
            except json.JSONDecodeError:
                pass
    return plugins


def resolve_plugin(state, spec):
    """'plugin' or 'plugin@marketplace' -> (plugin_name, mp_name, info)."""
    plugin, _, mp = spec.partition('@')
    candidates = []
    for mp_name in state['marketplaces']:
        if mp and mp_name != mp:
            continue
        mp_dir = marketplace_path(mp_name)
        if not mp_dir.exists():
            continue
        plugins = marketplace_plugins(mp_dir)
        if plugin in plugins:
            candidates.append((plugin, mp_name, plugins[plugin]))
    if not candidates:
        die(f"plugin '{spec}' not found in any marketplace (try 'list')")
    if len(candidates) > 1:
        names = ', '.join(f'{p}@{m}' for p, m, _ in candidates)
        die(f"ambiguous plugin '{plugin}': {names} — use plugin@marketplace")
    return candidates[0]


# ---------- install / uninstall ----------

def target_roots(project):
    if project:
        root = pathlib.Path(project).resolve()
        if not root.exists():
            die(f'project path {root} does not exist')
        return {
            'kilo_skills': root / '.kilo' / 'skills',
            'kilo_agents': root / '.kilo' / 'agent',
            'kilo_commands': root / '.kilo' / 'command',
            'claude_agents': root / '.claude' / 'agents',
            'claude_commands': root / '.claude' / 'commands',
            'claude_parent': root / '.claude',
        }, str(root)
    return {
        'kilo_skills': KILO_HOME / 'skills',
        'kilo_agents': KILO_HOME / 'agent',
        'kilo_commands': KILO_HOME / 'command',
        'claude_agents': CLAUDE_HOME / 'agents',
        'claude_commands': CLAUDE_HOME / 'commands',
        'claude_parent': CLAUDE_HOME,
    }, 'global'


# Skills are deliberately NOT mirrored into .claude/skills, by symlink or copy.
# Claude Code has its own mechanism for exactly this - a marketplace registered in
# extraKnownMarketplaces plus the plugin switched on in enabledPlugins, which can
# live in a project's settings.json and travel with the repo. Bridging the two
# directories duplicated that mechanism, and the copy always won: a directory
# nobody's tool declares is one that nothing updates and nothing reports as stale.
# This script installs for Kilo, which has no equivalent for git-based
# marketplaces; the Claude side is a one-line declaration the user owns.


def place_entry(dest, writer, kind, prev_paths, recorded):
    """Write/link dest unless a foreign file is in the way. Returns True if placed."""
    if dest.exists() or dest.is_symlink():
        if str(dest) in prev_paths:
            if dest.is_dir() and not dest.is_symlink():
                shutil.rmtree(dest)
            else:
                dest.unlink()
        else:
            print(f'[skip] {dest} exists and was not installed by this tool — left alone')
            return False
    dest.parent.mkdir(parents=True, exist_ok=True)
    writer(dest)
    recorded.append({'path': str(dest), 'kind': kind})
    return True


def install_plugin(state, plugin, mp_name, info, project, copy, include_claude):
    roots, target_key = target_roots(project)
    key = f'{plugin}@{mp_name}'
    prev = state['installs'].get(key, {}).get('targets', {}).get(target_key, {})
    prev_paths = {e['path'] for e in prev.get('files', [])}
    recorded = []
    ppath = info['path']

    skills_src = ppath / 'skills'
    if skills_src.is_dir():
        for sd in sorted(skills_src.iterdir()):
            if not (sd / 'SKILL.md').exists():
                continue
            fm, _ = parse_fm((sd / 'SKILL.md').read_text())
            if 'name' not in fm or 'description' not in fm:
                print(f'[warn] skill {sd.name}: SKILL.md missing name/description '
                      f'frontmatter (fix it in the plugin source)')
            dest = roots['kilo_skills'] / sd.name
            if copy:
                ok = place_entry(dest, lambda d, s=sd: shutil.copytree(s, d), 'dir',
                                 prev_paths, recorded)
            else:
                ok = place_entry(dest, lambda d, s=sd: d.symlink_to(s.resolve(),
                                 target_is_directory=True), 'symlink', prev_paths, recorded)
            if ok:
                print(f'[skill] {sd.name} -> {dest}')

    # Per-file fallback, not per-directory: a hand-written Kilo override in
    # agents_kilo/ (or agents/kilo/) is used only for the agents that
    # actually have one there; every other agent still falls back to
    # auto-translating its plain agents/ source. Picking a whole directory
    # (the old behavior) silently dropped Kilo generation for every agent
    # *not* covered by a partial agents_kilo/ override.
    kilo_override_dir = (ppath / 'agents_kilo' if (ppath / 'agents_kilo').is_dir()
                          else (ppath / 'agents' / 'kilo' if (ppath / 'agents' / 'kilo').is_dir() else None))
    claude_agents_dir = ppath / 'agents'
    agent_names = set()
    if kilo_override_dir:
        agent_names |= {f.name for f in kilo_override_dir.glob('*.md') if f.is_file()}
    if claude_agents_dir.is_dir():
        agent_names |= {f.name for f in claude_agents_dir.glob('*.md') if f.is_file()}
    for fname in sorted(agent_names):
        override = kilo_override_dir / fname if kilo_override_dir else None
        src = override if (override and override.is_file()) else claude_agents_dir / fname
        if not src.is_file():
            continue
        text = src.read_text()
        fields, body = parse_fm(text)
        name = fields.get('name', src.stem)
        kilo_text = text if is_kilo_shaped(fields) else to_kilo_agent(name, fields, body)
        dest = roots['kilo_agents'] / fname
        if place_entry(dest, lambda d, t=kilo_text: d.write_text(t), 'file',
                       prev_paths, recorded):
            print(f'[agent] {src.stem} -> {dest} (kilo)')

    claude_agents_src = ppath / 'agents'
    if include_claude and claude_agents_src.is_dir():
        for f in sorted(claude_agents_src.glob('*.md')):
            if f.is_file():
                text = f.read_text()
                fields, body = parse_fm(text)
                name = fields.get('name', f.stem)
                claude_text = (to_claude_agent(name, fields, body)
                               if is_kilo_shaped(fields) else text)
                dest = roots['claude_agents'] / f.name
                if place_entry(dest, lambda d, t=claude_text: d.write_text(t), 'file',
                               prev_paths, recorded):
                    print(f'[agent] {f.stem} -> {dest} (claude)')

    commands_src = ppath / 'commands'
    if commands_src.is_dir():
        for f in sorted(commands_src.glob('*.md')):
            for tkey in (['kilo_commands', 'claude_commands'] if include_claude
                         else ['kilo_commands']):
                dest = roots[tkey] / f.name
                if place_entry(dest, lambda d, s=f: d.symlink_to(s.resolve()),
                               'symlink', prev_paths, recorded):
                    print(f'[command] {f.name} -> {dest}')

    # anything previously recorded but no longer produced (removed upstream)
    for stale in prev_paths - {e['path'] for e in recorded}:
        p = pathlib.Path(stale)
        if p.is_symlink() or p.is_file():
            p.unlink()
            print(f'[clean] removed stale {stale}')
        elif p.is_dir():
            shutil.rmtree(p)
            print(f'[clean] removed stale {stale}')

    entry = state['installs'].setdefault(key, {'targets': {}})
    entry['targets'][target_key] = {
        'project': project and str(pathlib.Path(project).resolve()),
        'copy': copy, 'claude': include_claude,
        'version': info.get('version'), 'files': recorded,
    }
    save_state(state)


def uninstall_plugin(state, spec, project):
    plugin, _, mp = spec.partition('@')
    _, target_key = target_roots(project)
    matches = [k for k in state['installs']
               if k.split('@')[0] == plugin and (not mp or k.endswith('@' + mp))]
    if not matches:
        die(f"no recorded install for '{spec}'")
    if len(matches) > 1:
        die(f"ambiguous: {', '.join(matches)} — use plugin@marketplace")
    key = matches[0]
    tgt = state['installs'][key]['targets'].pop(target_key, None)
    if tgt is None:
        die(f"'{key}' is not installed for target '{target_key}'")
    for e in tgt['files']:
        p = pathlib.Path(e['path'])
        if p.is_symlink() or p.is_file():
            p.unlink()
        elif p.is_dir():
            shutil.rmtree(p)
        print(f'[removed] {e["path"]}')
    if not state['installs'][key]['targets']:
        del state['installs'][key]
    save_state(state)


# ---------- commands ----------

def cmd_add(args, state):
    url = args.url
    src = pathlib.Path(url).expanduser()
    if src.exists():
        url = str(src.resolve())
    name = args.name
    if not name:
        name = re.sub(r'\.git$', '', url.rstrip('/').split('/')[-1])
    dest = marketplace_path(name)
    if dest.exists():
        recorded = state['marketplaces'].get(name, {}).get('url')
        if recorded and recorded != url:
            die(f"marketplace '{name}' already exists with url {recorded}")
        run_git(['pull', '--ff-only'], cwd=dest)
        print(f'[marketplace] refreshed {name}')
    else:
        MARKETPLACES_DIR.mkdir(parents=True, exist_ok=True)
        run_git(['clone', url, str(dest)])
        print(f'[marketplace] added {name} -> {dest}')
    manifest = dest / '.claude-plugin' / 'marketplace.json'
    if manifest.exists():
        canonical = json.loads(manifest.read_text()).get('name')
        if canonical and canonical != name and not args.name:
            print(f"[note] marketplace declares name '{canonical}'; using directory name '{name}'")
    state['marketplaces'][name] = {'url': url}
    save_state(state)
    cmd_list(argparse.Namespace(marketplace=name), state)


def cmd_remove(args, state):
    name = args.marketplace
    if name not in state['marketplaces']:
        die(f"unknown marketplace '{name}'")
    live = [k for k in state['installs'] if k.endswith('@' + name)]
    if live and not args.force:
        die(f"plugins still installed from '{name}': {', '.join(live)} — "
            f'uninstall them first or use --force')
    dest = marketplace_path(name)
    if dest.exists():
        shutil.rmtree(dest)
    del state['marketplaces'][name]
    save_state(state)
    print(f'[marketplace] removed {name}')


def cmd_list(args, state):
    if not state['marketplaces']:
        print('no marketplaces registered (use: add <git-url>)')
        return
    for mp_name in sorted(state['marketplaces']):
        mp_dir = marketplace_path(mp_name)
        print(f'{mp_name}  ({state["marketplaces"][mp_name]["url"]})')
        if getattr(args, 'marketplace', None) and args.marketplace != mp_name:
            continue
        if not mp_dir.exists():
            print('  [missing checkout — re-run add]')
            continue
        for pname, info in sorted(marketplace_plugins(mp_dir).items()):
            key = f'{pname}@{mp_name}'
            targets = state['installs'].get(key, {}).get('targets', {})
            marks = []
            for tkey, tinfo in targets.items():
                v = tinfo.get('version')
                marks.append(f'installed:{tkey}' + (f' (v{v})' if v else ''))
            ver = f" v{info['version']}" if info.get('version') else ''
            status = f"  [{'; '.join(marks)}]" if marks else ''
            print(f'  {pname}{ver}  {info["description"]}{status}')


def cmd_install(args, state):
    plugin, mp_name, info = resolve_plugin(state, args.plugin)
    install_plugin(state, plugin, mp_name, info, args.project, args.copy,
                   not args.no_claude)
    print(f'[done] {plugin}@{mp_name} installed'
          + (f' into {args.project}' if args.project else ' globally'))


def cmd_uninstall(args, state):
    uninstall_plugin(state, args.plugin, args.project)


def cmd_update(args, state):
    names = [args.marketplace] if args.marketplace else sorted(state['marketplaces'])
    for name in names:
        dest = marketplace_path(name)
        if not dest.exists():
            print(f'[warn] {name}: checkout missing, skipping')
            continue
        try:
            run_git(['pull', '--ff-only'], cwd=dest)
            print(f'[marketplace] {name} updated ({run_git(["rev-parse", "--short", "HEAD"], cwd=dest)})')
        except RuntimeError as e:
            print(f'[warn] {name}: {e}')
            continue
    # refresh every recorded install (symlinks follow automatically; agents/copies regenerate)
    for key, entry in list(state['installs'].items()):
        plugin, _, mp_name = key.partition('@')
        if args.marketplace and mp_name != args.marketplace:
            continue
        mp_dir = marketplace_path(mp_name)
        if not mp_dir.exists():
            continue
        plugins = marketplace_plugins(mp_dir)
        if plugin not in plugins:
            print(f'[warn] {key}: plugin no longer in marketplace, leaving install as-is')
            continue
        for tkey, tinfo in list(entry['targets'].items()):
            install_plugin(state, plugin, mp_name, plugins[plugin],
                           tinfo.get('project'), tinfo.get('copy', False),
                           tinfo.get('claude', True))
            print(f'[refresh] {key} @ {tkey}')


def cmd_status(args, state):
    print(f'state: {STATE_PATH}')
    for name in sorted(state['marketplaces']):
        dest = marketplace_path(name)
        head = '?'
        if dest.exists():
            try:
                head = run_git(['log', '-1', '--format=%h %ad %s', '--date=short'], cwd=dest)
            except RuntimeError:
                pass
        print(f'marketplace {name}: {state["marketplaces"][name]["url"]}\n  HEAD: {head}')
    for key, entry in sorted(state['installs'].items()):
        for tkey, tinfo in entry['targets'].items():
            v = tinfo.get('version')
            print(f'install {key} @ {tkey}'
                  + (f' v{v}' if v else '') + f' ({len(tinfo["files"])} files)')


def cmd_convert(args, state):
    out = translate_agent(args.file, args.to)
    if args.output:
        pathlib.Path(args.output).write_text(out)
        print(f'wrote {args.output}')
    else:
        sys.stdout.write(out)


def cmd_init_marketplace(args, state):
    root = pathlib.Path(args.path).resolve()
    name = args.name or root.name
    if (root / '.claude-plugin').exists():
        die(f'{root} already looks like a marketplace')
    example = 'example-plugin'
    (root / '.claude-plugin').mkdir(parents=True)
    (root / '.claude-plugin' / 'marketplace.json').write_text(json.dumps({
        'name': name,
        'owner': {'name': 'D4Science - gCube'},
        'plugins': [{'name': example, 'source': f'./plugins/{example}',
                     'description': 'Example plugin — rename or remove'}],
    }, indent=2) + '\n')
    pdir = root / 'plugins' / example
    (pdir / '.claude-plugin').mkdir(parents=True)
    (pdir / '.claude-plugin' / 'plugin.json').write_text(json.dumps({
        'name': example, 'version': '0.1.0',
        'description': 'Example plugin — rename or remove',
    }, indent=2) + '\n')
    (pdir / 'skills' / 'example-skill').mkdir(parents=True)
    (pdir / 'skills' / 'example-skill' / 'SKILL.md').write_text(
        '---\nname: example-skill\ndescription: Replace with a real skill.\n---\n\n'
        '# Example skill\n\nReplace me.\n')
    (pdir / 'agents').mkdir()
    (pdir / 'agents' / 'example-agent.md').write_text(
        '---\nname: example-agent\ndescription: Replace with a real agent.\n'
        'tools: Bash, Read, Edit, Write, Grep, Glob\n---\n\n'
        '# Example agent\n\nReplace me.\n')
    (pdir / 'commands').mkdir()
    (root / 'README.md').write_text(
        f'# {name} — agent/skill marketplace\n\n'
        '## Claude Code (native)\n\n'
        f'    claude plugin marketplace add <git-url>\n'
        f'    /plugin install {example}@{name}\n\n'
        '## Kilo Code and other tools (kilo-plugin-manager)\n\n'
        f'    plugin_manager.py add <git-url> --name {name}\n'
        f'    plugin_manager.py install {example}@{name} [--project <repo>]\n'
        f'    plugin_manager.py update\n')
    if not (root / '.git').exists():
        run_git(['init'], cwd=root)
    print(f'[scaffold] marketplace {name} created at {root}')


# ---------- agent sync between the two hosts ----------
#
# Absorbed from the former kilo-claude-sync skill. Agents are the one thing that
# genuinely needs a bridge: each host demands its own frontmatter shape, so the
# shared description and body have to exist twice. Skills do not - both hosts
# install those natively (see the note above install_plugin).
#
# The translation itself reuses to_kilo_agent()/to_claude_agent() above, which is
# why this lives here now: two copies of one frontmatter translator is how they
# drift apart.

def agent_read(path):
    if not path.exists():
        return None
    fields, body = parse_fm(path.read_text())
    other = [f'{k}: {v}' for k, v in fields.items() if k not in ('name', 'description')]
    return {'description': fields.get('description', ''), 'body': body,
            'fields': fields, 'other_lines': other}


def agent_hash(parsed):
    """Hashes only what the two sides share, so a change to one host's own
    frontmatter never reads as drift."""
    if parsed is None:
        return None
    return hashlib.sha256((parsed['description'] + '\x00' + parsed['body']).encode()).hexdigest()


def agent_write(path, name_field, description, other_lines, body):
    fm = ([f'name: {name_field}'] if name_field else []) \
        + [f'description: {sanitize_yaml_val(description)}'] + other_lines
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text('---\n' + '\n'.join(fm) + '\n---\n' + body)


def sync_agents_root(root):
    kilo_dir, claude_dir = root / '.kilo' / 'agent', root / '.claude' / 'agents'
    if not kilo_dir.exists() and not claude_dir.exists():
        return

    state_path = root / '.kilo-agent-sync-state.json'
    state = json.loads(state_path.read_text()) if state_path.exists() else {}
    dirty = False

    names = set()
    for d in (kilo_dir, claude_dir):
        if d.exists():
            names |= {p.stem for p in d.glob('*.md')}

    for name in sorted(names):
        kpath, cpath = kilo_dir / f'{name}.md', claude_dir / f'{name}.md'
        k, c = agent_read(kpath), agent_read(cpath)
        st = state.get(name, {})
        kh, ch = agent_hash(k), agent_hash(c)
        k_changed = k is not None and st.get('kilo') != kh
        c_changed = c is not None and st.get('claude') != ch

        if k and not c:
            cpath.parent.mkdir(parents=True, exist_ok=True)
            cpath.write_text(to_claude_agent(name, k['fields'], k['body'], mark=False))
            print(f'[agents] created {cpath} from {kpath}')
        elif c and not k:
            kpath.parent.mkdir(parents=True, exist_ok=True)
            kpath.write_text(to_kilo_agent(name, c['fields'], c['body'], mark=False))
            print(f'[agents] created {kpath} from {cpath}')
        elif k_changed and c_changed:
            if kh != ch:
                print(f"[agents] CONFLICT: '{name}' edited on both sides since the last sync - "
                      'resolve by hand, then re-run.')
                continue
            # Identical on both sides (e.g. both just installed): only record state.
        elif k_changed:
            # Regenerate the stale side but keep ITS own frontmatter: a hand-tuned
            # tools: line on the Claude file is not the Kilo file's business.
            agent_write(cpath, name, k['description'], c['other_lines'], k['body'])
            print(f"[agents] synced '{name}' kilo -> claude")
        elif c_changed:
            agent_write(kpath, None, c['description'], k['other_lines'], c['body'])
            print(f"[agents] synced '{name}' claude -> kilo")
        else:
            continue

        k, c = agent_read(kpath), agent_read(cpath)
        state[name] = {'kilo': agent_hash(k), 'claude': agent_hash(c)}
        dirty = True

    if dirty:
        state_path.write_text(json.dumps(state, indent=2) + '\n')


def find_git_root(start):
    p = pathlib.Path(start).resolve()
    for parent in [p] + list(p.parents):
        if (parent / '.git').exists():
            return parent
    return None


def cmd_sync_agents(args, state):
    roots = []
    if args.scope in ('local', 'both'):
        git_root = find_git_root(args.repo)
        if git_root:
            roots.append(('local', git_root))
        else:
            print(f'no git repo found at {args.repo}, skipping local scope', file=sys.stderr)
    if args.scope in ('global', 'both'):
        roots.append(('global', ROOT))
    for label, root in roots:
        print(f'== {label}: {root} ==')
        sync_agents_root(root)


# ---------- moving hand-authored items between global and project scope ----------
#
# Absorbed from the former kilo-scope-manager skill. It is here rather than in its
# own tool because it needs the same knowledge this file already encodes: where
# each kind of item lives on disk. Two tables that must agree about that is one
# table too many.
#
# The `~/.config/kilo` locations below are the reason this is not just a `mv`:
# Kilo reads agents and commands from there, skills from ~/.kilo, and a twin left
# in the other location silently shadows the one being edited.

MOVE_KINDS = {
    'skill': {'local': lambda repo: repo / '.kilo' / 'skills',
              'global': ROOT / '.kilo' / 'skills',
              'other_globals': [ROOT / '.config' / 'kilo' / 'skills'],
              'is_dir': True},
    'agent': {'local': lambda repo: repo / '.kilo' / 'agent',
              'global': ROOT / '.config' / 'kilo' / 'agent',
              'other_globals': [ROOT / '.kilo' / 'agent'],
              'is_dir': False},
    'command': {'local': lambda repo: repo / '.kilo' / 'command',
                'global': ROOT / '.config' / 'kilo' / 'command',
                'other_globals': [ROOT / '.kilo' / 'command'],
                'is_dir': False},
}


def move_item_path(base, name, is_dir):
    return base / name if is_dir else base / f'{name}.md'


def move_validate(kind, path, is_dir):
    md = path / 'SKILL.md' if is_dir else path
    if not md.is_file():
        die(f"{path} is not a valid {kind} ({'no SKILL.md' if is_dir else 'file missing'})")
    head = md.read_text(encoding='utf-8', errors='replace').splitlines()[:12]
    if kind == 'skill' and not any(l.startswith('name:') for l in head):
        print(f"WARNING: {md} has no 'name:' frontmatter (required for skill discovery)")
    if kind in ('agent', 'command') and not any(l.startswith('description:') for l in head):
        print(f"WARNING: {md} has no 'description:' frontmatter")


def cmd_move(args, state):
    cfg = MOVE_KINDS[args.kind]
    repo = find_git_root(args.repo) or pathlib.Path(args.repo).resolve()
    local_base, global_base = cfg['local'](repo), cfg['global']
    src_base, dst_base = ((global_base, local_base) if args.direction == 'to-local'
                          else (local_base, global_base))
    src = move_item_path(src_base, args.name, cfg['is_dir'])
    dst = move_item_path(dst_base, args.name, cfg['is_dir'])

    if not (src.is_dir() if cfg['is_dir'] else src.is_file()):
        die(f'source {args.kind} not found: {src}')
    move_validate(args.kind, src, cfg['is_dir'])

    if dst.exists():
        if not args.force:
            die(f'destination already exists: {dst} (use --force to overwrite)')
        shutil.rmtree(dst) if dst.is_dir() else dst.unlink()

    dst.parent.mkdir(parents=True, exist_ok=True)
    if args.copy:
        shutil.copytree(src, dst, symlinks=True) if cfg['is_dir'] else shutil.copy2(src, dst)
        action = 'copied'
    else:
        shutil.move(str(src), str(dst))
        action = 'moved'
    print(f'OK: {action} {src} -> {dst}')

    if args.copy and args.direction == 'to-local':
        print('NOTE: the local copy shadows the global item of the same name (project wins).')
    for og in cfg['other_globals']:
        twin = move_item_path(og, args.name, cfg['is_dir'])
        if twin.exists():
            print(f'WARNING: another copy exists at {twin} - check which one your Kilo version '
                  'loads and remove the stale twin.')
    if args.kind in ('agent', 'command'):
        print("NOTE: agents are mirrored to Claude Code - run 'sync-agents' for the affected scope.")
    else:
        print('NOTE: Claude Code is unaffected - it installs skills through its own marketplace.')
    print('Run /reload in Kilo to pick up the change in the current session.')


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    sub = ap.add_subparsers(dest='cmd', required=True)

    p = sub.add_parser('add', help='register + clone a marketplace git repo')
    p.add_argument('url')
    p.add_argument('--name')
    p.set_defaults(fn=cmd_add)

    p = sub.add_parser('remove', help='remove a marketplace checkout')
    p.add_argument('marketplace')
    p.add_argument('--force', action='store_true')
    p.set_defaults(fn=cmd_remove)

    p = sub.add_parser('list', help='list plugins in all marketplaces')
    p.add_argument('marketplace', nargs='?')
    p.set_defaults(fn=cmd_list)

    p = sub.add_parser('install', help='install a plugin (global or --project)')
    p.add_argument('plugin', help='plugin or plugin@marketplace')
    p.add_argument('--project', help='install into this repo instead of globally')
    p.add_argument('--copy', action='store_true',
                   help='copy skills instead of symlinking (survives marketplace removal)')
    p.add_argument('--no-claude', action='store_true',
                   help='skip .claude/agents and .claude/commands generation')
    p.set_defaults(fn=cmd_install)

    p = sub.add_parser('uninstall', help='remove an installed plugin')
    p.add_argument('plugin')
    p.add_argument('--project')
    p.set_defaults(fn=cmd_uninstall)

    p = sub.add_parser('update', help='git pull marketplaces + refresh installs')
    p.add_argument('marketplace', nargs='?')
    p.set_defaults(fn=cmd_update)

    p = sub.add_parser('status', help='show marketplaces and installs')
    p.set_defaults(fn=cmd_status)

    p = sub.add_parser('convert', help='translate one agent .md between formats')
    p.add_argument('file')
    p.add_argument('--to', choices=['kilo', 'claude'], required=True)
    p.add_argument('-o', '--output')
    p.set_defaults(fn=cmd_convert)

    p = sub.add_parser('move', help='move/copy a hand-authored item between global and local scope')
    p.add_argument('kind', choices=sorted(MOVE_KINDS))
    p.add_argument('direction', choices=['to-local', 'to-global'])
    p.add_argument('name', help='skill directory name, or agent/command filename without .md')
    p.add_argument('--repo', default='.', help='project path (default: cwd, resolved to git root)')
    p.add_argument('--copy', action='store_true', help='copy instead of move')
    p.add_argument('--force', action='store_true', help='overwrite the destination if it exists')
    p.set_defaults(fn=cmd_move)

    p = sub.add_parser('sync-agents', help='align .kilo/agent and .claude/agents (agents only)')
    p.add_argument('--scope', choices=['local', 'global', 'both'], default='both')
    p.add_argument('--repo', default='.')
    p.set_defaults(fn=cmd_sync_agents)

    p = sub.add_parser('init-marketplace', help='scaffold a new marketplace repo')
    p.add_argument('path')
    p.add_argument('--name')
    p.set_defaults(fn=cmd_init_marketplace)

    args = ap.parse_args()
    args.fn(args, load_state())


if __name__ == '__main__':
    main()
