#!/usr/bin/env python3
"""Plugin marketplace manager for Kilo Code (and Claude Code).

Emulates Claude Code's native plugin-marketplace mechanism for tools that
lack it. A "marketplace" is any git repo laid out in Claude Code's plugin
format (`.claude-plugin/marketplace.json` + plugin dirs with `skills/`,
`agents/`, `commands/`), so the SAME repo serves Claude Code users natively
and Kilo/other users through this script.

Subcommands:
  add <git-url-or-path> [--name N]   clone/refresh a marketplace under ~/.kilo/marketplaces/
  remove <marketplace>               drop a marketplace checkout (warns about live installs)
  list                               show available plugins with installed state/version
  install <plugin>[@marketplace]     symlink skills, generate agents/commands
          [--project PATH] [--copy] [--no-claude]
  uninstall <plugin>[@marketplace] [--project PATH]
  update [marketplace]               git pull marketplaces + refresh every recorded install
  status                             marketplaces, HEAD commits, recorded installs
  convert <file.md> --to kilo|claude [-o OUT]   translate one agent file's frontmatter
  init-marketplace <path> [--name N] scaffold a new marketplace repo

State lives in ~/.kilo/plugin-manager.json. Only paths recorded there are
ever overwritten or removed; anything else is warned about and left alone.
Set KILO_PM_ROOT to relocate ~ for testing.
"""
import argparse
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys

ROOT = pathlib.Path(os.environ.get('KILO_PM_ROOT', str(pathlib.Path.home())))
KILO_HOME = ROOT / '.kilo'
CLAUDE_HOME = ROOT / '.claude'
MARKETPLACES_DIR = KILO_HOME / 'marketplaces'
STATE_PATH = KILO_HOME / 'plugin-manager.json'

FRONTMATTER_RE = re.compile(r'^---\n(.*?)\n---\n?(.*)$', re.DOTALL)

# Claude tool name (lowercased) -> Kilo permission key
TOOL_PERMISSION_MAP = {
    'read': 'read', 'grep': 'read', 'glob': 'read',
    'edit': 'edit', 'write': 'edit', 'notebookedit': 'edit',
    'bash': 'bash',
    'webfetch': 'webfetch', 'websearch': 'webfetch',
    'skill': 'skill',
}
# Kilo permission key -> Claude tool names
PERMISSION_TOOL_MAP = {
    'read': ['Read', 'Grep', 'Glob'],
    'edit': ['Edit', 'Write'],
    'bash': ['Bash'],
    'webfetch': ['WebFetch', 'WebSearch'],
    'skill': ['Skill'],
}
KILO_PERMISSION_ORDER = ['read', 'edit', 'bash', 'skill', 'webfetch', 'mcp']
DEFAULT_KILO_PERMISSIONS = ['read', 'edit', 'bash', 'skill', 'webfetch']
GENERATED_MARK = '# generated by kilo-plugin-manager — edit the plugin source, not this file'


def die(msg):
    print(f'error: {msg}', file=sys.stderr)
    sys.exit(1)


def run_git(args, cwd=None):
    r = subprocess.run(['git'] + args, cwd=cwd, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {r.stderr.strip()}")
    return r.stdout.strip()


def load_state():
    if STATE_PATH.exists():
        return json.loads(STATE_PATH.read_text())
    return {'marketplaces': {}, 'installs': {}}


def save_state(state):
    STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    STATE_PATH.write_text(json.dumps(state, indent=2) + '\n')


# ---------- frontmatter parsing / agent translation ----------

def parse_fm(text):
    """Flat-ish frontmatter parser: top-level `key: value` pairs; indented
    continuation lines (nested blocks like Kilo's `permission:`) are kept
    verbatim appended to their key's raw value."""
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, text
    fields, current = {}, None
    for line in m.group(1).split('\n'):
        if line.lstrip().startswith('#'):
            continue
        km = re.match(r'^([A-Za-z0-9_-]+)\s*:(.*)$', line)
        if km:
            current = km.group(1)
            fields[current] = km.group(2).strip()
        elif current is not None:
            fields[current] += '\n' + line
    return fields, m.group(2)


def is_kilo_shaped(fields):
    return 'mode' in fields or 'permission' in fields


def tools_to_permissions(tools_val):
    perms = set()
    for t in re.split(r'[,\s]+', tools_val):
        t = t.strip().lower()
        if not t:
            continue
        if t.startswith('mcp__') or t == 'mcp':
            perms.add('mcp')
        elif t in TOOL_PERMISSION_MAP:
            perms.add(TOOL_PERMISSION_MAP[t])
    return perms or set(DEFAULT_KILO_PERMISSIONS)


def to_kilo_agent(name, fields, body, mark=True):
    if 'tools' in fields:
        perms = tools_to_permissions(fields['tools'])
    else:
        perms = set(DEFAULT_KILO_PERMISSIONS)
    lines = ['---']
    if mark:
        lines.append(GENERATED_MARK)
    lines += [f'name: {name}',
              f"description: {fields.get('description', '')}",
              f"mode: {fields.get('mode', 'primary').split(chr(10))[0] or 'primary'}",
              'permission:']
    lines += [f'  {p}: allow' for p in KILO_PERMISSION_ORDER if p in perms]
    lines.append('---')
    return '\n'.join(lines) + '\n' + body


def to_claude_agent(name, fields, body, mark=True):
    perm_raw = fields.get('permission', '')
    tools = []
    if perm_raw:
        for key, names in PERMISSION_TOOL_MAP.items():
            if re.search(rf'\b{key}\s*:\s*allow', perm_raw):
                tools += names
    if not tools:
        tools = [t for names in PERMISSION_TOOL_MAP.values() for t in names]
    lines = ['---']
    if mark:
        lines.append(GENERATED_MARK)
    lines += [f'name: {name}',
              f"description: {fields.get('description', '')}",
              f"tools: {', '.join(tools)}",
              '---']
    return '\n'.join(lines) + '\n' + body


def translate_agent(src_path, to):
    text = pathlib.Path(src_path).read_text()
    fields, body = parse_fm(text)
    name = fields.get('name', pathlib.Path(src_path).stem)
    if to == 'kilo':
        return text if is_kilo_shaped(fields) else to_kilo_agent(name, fields, body)
    return to_claude_agent(name, fields, body) if is_kilo_shaped(fields) else text


# ---------- marketplace discovery ----------

def marketplace_path(name):
    return MARKETPLACES_DIR / name


def marketplace_plugins(mp_path):
    """Return {plugin_name: {path, description, version}} for a marketplace
    checkout. Prefers .claude-plugin/marketplace.json; falls back to scanning
    plugins/ (or top-level) for dirs containing skills/agents/commands."""
    plugins = {}
    manifest = mp_path / '.claude-plugin' / 'marketplace.json'
    if manifest.exists():
        data = json.loads(manifest.read_text())
        for p in data.get('plugins', []):
            src = p.get('source', f"./plugins/{p['name']}")
            if not isinstance(src, str):
                continue  # external plugin sources not supported here
            plugins[p['name']] = {'path': (mp_path / src).resolve(),
                                  'description': p.get('description', '')}
    else:
        base = mp_path / 'plugins' if (mp_path / 'plugins').is_dir() else mp_path
        for d in sorted(base.iterdir()):
            if d.name.startswith('.') or not d.is_dir():
                continue
            if any((d / s).exists() for s in ('skills', 'agents', 'commands', '.claude-plugin')):
                plugins[d.name] = {'path': d, 'description': ''}
    for info in plugins.values():
        info.setdefault('version', None)
        pj = info['path'] / '.claude-plugin' / 'plugin.json'
        if pj.exists():
            try:
                pdata = json.loads(pj.read_text())
                info['version'] = pdata.get('version')
                info['description'] = info['description'] or pdata.get('description', '')
            except json.JSONDecodeError:
                pass
    return plugins


def resolve_plugin(state, spec):
    """'plugin' or 'plugin@marketplace' -> (plugin_name, mp_name, info)."""
    plugin, _, mp = spec.partition('@')
    candidates = []
    for mp_name in state['marketplaces']:
        if mp and mp_name != mp:
            continue
        mp_dir = marketplace_path(mp_name)
        if not mp_dir.exists():
            continue
        plugins = marketplace_plugins(mp_dir)
        if plugin in plugins:
            candidates.append((plugin, mp_name, plugins[plugin]))
    if not candidates:
        die(f"plugin '{spec}' not found in any marketplace (try 'list')")
    if len(candidates) > 1:
        names = ', '.join(f'{p}@{m}' for p, m, _ in candidates)
        die(f"ambiguous plugin '{plugin}': {names} — use plugin@marketplace")
    return candidates[0]


# ---------- install / uninstall ----------

def target_roots(project):
    if project:
        root = pathlib.Path(project).resolve()
        if not root.exists():
            die(f'project path {root} does not exist')
        return {
            'kilo_skills': root / '.kilo' / 'skills',
            'kilo_agents': root / '.kilo' / 'agent',
            'kilo_commands': root / '.kilo' / 'command',
            'claude_agents': root / '.claude' / 'agents',
            'claude_commands': root / '.claude' / 'commands',
            'claude_parent': root / '.claude',
        }, str(root)
    return {
        'kilo_skills': KILO_HOME / 'skills',
        'kilo_agents': KILO_HOME / 'agent',
        'kilo_commands': KILO_HOME / 'command',
        'claude_agents': CLAUDE_HOME / 'agents',
        'claude_commands': CLAUDE_HOME / 'commands',
        'claude_parent': CLAUDE_HOME,
    }, 'global'


def ensure_claude_skills_symlink(roots):
    """Make .claude/skills point at .kilo/skills (same convention as
    kilo-claude-sync) so installed skills are visible to Claude Code too."""
    claude_skills = roots['claude_parent'] / 'skills'
    kilo_skills = roots['kilo_skills']
    if claude_skills.exists() or claude_skills.is_symlink():
        return
    if not kilo_skills.exists():
        return
    roots['claude_parent'].mkdir(parents=True, exist_ok=True)
    rel = os.path.relpath(kilo_skills, roots['claude_parent'])
    claude_skills.symlink_to(rel, target_is_directory=True)
    print(f'[skills] linked {claude_skills} -> {rel}')


def place_entry(dest, writer, kind, prev_paths, recorded):
    """Write/link dest unless a foreign file is in the way. Returns True if placed."""
    if dest.exists() or dest.is_symlink():
        if str(dest) in prev_paths:
            if dest.is_dir() and not dest.is_symlink():
                shutil.rmtree(dest)
            else:
                dest.unlink()
        else:
            print(f'[skip] {dest} exists and was not installed by this tool — left alone')
            return False
    dest.parent.mkdir(parents=True, exist_ok=True)
    writer(dest)
    recorded.append({'path': str(dest), 'kind': kind})
    return True


def install_plugin(state, plugin, mp_name, info, project, copy, include_claude):
    roots, target_key = target_roots(project)
    key = f'{plugin}@{mp_name}'
    prev = state['installs'].get(key, {}).get('targets', {}).get(target_key, {})
    prev_paths = {e['path'] for e in prev.get('files', [])}
    recorded = []
    ppath = info['path']

    skills_src = ppath / 'skills'
    if skills_src.is_dir():
        for sd in sorted(skills_src.iterdir()):
            if not (sd / 'SKILL.md').exists():
                continue
            fm, _ = parse_fm((sd / 'SKILL.md').read_text())
            if 'name' not in fm or 'description' not in fm:
                print(f'[warn] skill {sd.name}: SKILL.md missing name/description '
                      f'frontmatter (fix it in the plugin source)')
            dest = roots['kilo_skills'] / sd.name
            if copy:
                ok = place_entry(dest, lambda d, s=sd: shutil.copytree(s, d), 'dir',
                                 prev_paths, recorded)
            else:
                ok = place_entry(dest, lambda d, s=sd: d.symlink_to(s.resolve(),
                                 target_is_directory=True), 'symlink', prev_paths, recorded)
            if ok:
                print(f'[skill] {sd.name} -> {dest}')
        ensure_claude_skills_symlink(roots)

    kilo_agents_src = ppath / 'agents_kilo' if (ppath / 'agents_kilo').is_dir() else (ppath / 'agents' / 'kilo' if (ppath / 'agents' / 'kilo').is_dir() else ppath / 'agents')
    if kilo_agents_src.is_dir():
        for f in sorted(kilo_agents_src.glob('*.md')):
            if f.is_file():
                text = f.read_text()
                fields, body = parse_fm(text)
                name = fields.get('name', f.stem)
                kilo_text = (text if is_kilo_shaped(fields)
                             else to_kilo_agent(name, fields, body))
                dest = roots['kilo_agents'] / f.name
                if place_entry(dest, lambda d, t=kilo_text: d.write_text(t), 'file',
                               prev_paths, recorded):
                    print(f'[agent] {f.stem} -> {dest} (kilo)')

    claude_agents_src = ppath / 'agents'
    if include_claude and claude_agents_src.is_dir():
        for f in sorted(claude_agents_src.glob('*.md')):
            if f.is_file():
                text = f.read_text()
                fields, body = parse_fm(text)
                name = fields.get('name', f.stem)
                claude_text = (to_claude_agent(name, fields, body)
                               if is_kilo_shaped(fields) else text)
                dest = roots['claude_agents'] / f.name
                if place_entry(dest, lambda d, t=claude_text: d.write_text(t), 'file',
                               prev_paths, recorded):
                    print(f'[agent] {f.stem} -> {dest} (claude)')

    commands_src = ppath / 'commands'
    if commands_src.is_dir():
        for f in sorted(commands_src.glob('*.md')):
            for tkey in (['kilo_commands', 'claude_commands'] if include_claude
                         else ['kilo_commands']):
                dest = roots[tkey] / f.name
                if place_entry(dest, lambda d, s=f: d.symlink_to(s.resolve()),
                               'symlink', prev_paths, recorded):
                    print(f'[command] {f.name} -> {dest}')

    # anything previously recorded but no longer produced (removed upstream)
    for stale in prev_paths - {e['path'] for e in recorded}:
        p = pathlib.Path(stale)
        if p.is_symlink() or p.is_file():
            p.unlink()
            print(f'[clean] removed stale {stale}')
        elif p.is_dir():
            shutil.rmtree(p)
            print(f'[clean] removed stale {stale}')

    entry = state['installs'].setdefault(key, {'targets': {}})
    entry['targets'][target_key] = {
        'project': project and str(pathlib.Path(project).resolve()),
        'copy': copy, 'claude': include_claude,
        'version': info.get('version'), 'files': recorded,
    }
    save_state(state)


def uninstall_plugin(state, spec, project):
    plugin, _, mp = spec.partition('@')
    _, target_key = target_roots(project)
    matches = [k for k in state['installs']
               if k.split('@')[0] == plugin and (not mp or k.endswith('@' + mp))]
    if not matches:
        die(f"no recorded install for '{spec}'")
    if len(matches) > 1:
        die(f"ambiguous: {', '.join(matches)} — use plugin@marketplace")
    key = matches[0]
    tgt = state['installs'][key]['targets'].pop(target_key, None)
    if tgt is None:
        die(f"'{key}' is not installed for target '{target_key}'")
    for e in tgt['files']:
        p = pathlib.Path(e['path'])
        if p.is_symlink() or p.is_file():
            p.unlink()
        elif p.is_dir():
            shutil.rmtree(p)
        print(f'[removed] {e["path"]}')
    if not state['installs'][key]['targets']:
        del state['installs'][key]
    save_state(state)


# ---------- commands ----------

def cmd_add(args, state):
    url = args.url
    src = pathlib.Path(url).expanduser()
    if src.exists():
        url = str(src.resolve())
    name = args.name
    if not name:
        name = re.sub(r'\.git$', '', url.rstrip('/').split('/')[-1])
    dest = marketplace_path(name)
    if dest.exists():
        recorded = state['marketplaces'].get(name, {}).get('url')
        if recorded and recorded != url:
            die(f"marketplace '{name}' already exists with url {recorded}")
        run_git(['pull', '--ff-only'], cwd=dest)
        print(f'[marketplace] refreshed {name}')
    else:
        MARKETPLACES_DIR.mkdir(parents=True, exist_ok=True)
        run_git(['clone', url, str(dest)])
        print(f'[marketplace] added {name} -> {dest}')
    manifest = dest / '.claude-plugin' / 'marketplace.json'
    if manifest.exists():
        canonical = json.loads(manifest.read_text()).get('name')
        if canonical and canonical != name and not args.name:
            print(f"[note] marketplace declares name '{canonical}'; using directory name '{name}'")
    state['marketplaces'][name] = {'url': url}
    save_state(state)
    cmd_list(argparse.Namespace(marketplace=name), state)


def cmd_remove(args, state):
    name = args.marketplace
    if name not in state['marketplaces']:
        die(f"unknown marketplace '{name}'")
    live = [k for k in state['installs'] if k.endswith('@' + name)]
    if live and not args.force:
        die(f"plugins still installed from '{name}': {', '.join(live)} — "
            f'uninstall them first or use --force')
    dest = marketplace_path(name)
    if dest.exists():
        shutil.rmtree(dest)
    del state['marketplaces'][name]
    save_state(state)
    print(f'[marketplace] removed {name}')


def cmd_list(args, state):
    if not state['marketplaces']:
        print('no marketplaces registered (use: add <git-url>)')
        return
    for mp_name in sorted(state['marketplaces']):
        mp_dir = marketplace_path(mp_name)
        print(f'{mp_name}  ({state["marketplaces"][mp_name]["url"]})')
        if getattr(args, 'marketplace', None) and args.marketplace != mp_name:
            continue
        if not mp_dir.exists():
            print('  [missing checkout — re-run add]')
            continue
        for pname, info in sorted(marketplace_plugins(mp_dir).items()):
            key = f'{pname}@{mp_name}'
            targets = state['installs'].get(key, {}).get('targets', {})
            marks = []
            for tkey, tinfo in targets.items():
                v = tinfo.get('version')
                marks.append(f'installed:{tkey}' + (f' (v{v})' if v else ''))
            ver = f" v{info['version']}" if info.get('version') else ''
            status = f"  [{'; '.join(marks)}]" if marks else ''
            print(f'  {pname}{ver}  {info["description"]}{status}')


def cmd_install(args, state):
    plugin, mp_name, info = resolve_plugin(state, args.plugin)
    install_plugin(state, plugin, mp_name, info, args.project, args.copy,
                   not args.no_claude)
    print(f'[done] {plugin}@{mp_name} installed'
          + (f' into {args.project}' if args.project else ' globally'))


def cmd_uninstall(args, state):
    uninstall_plugin(state, args.plugin, args.project)


def cmd_update(args, state):
    names = [args.marketplace] if args.marketplace else sorted(state['marketplaces'])
    for name in names:
        dest = marketplace_path(name)
        if not dest.exists():
            print(f'[warn] {name}: checkout missing, skipping')
            continue
        try:
            run_git(['pull', '--ff-only'], cwd=dest)
            print(f'[marketplace] {name} updated ({run_git(["rev-parse", "--short", "HEAD"], cwd=dest)})')
        except RuntimeError as e:
            print(f'[warn] {name}: {e}')
            continue
    # refresh every recorded install (symlinks follow automatically; agents/copies regenerate)
    for key, entry in list(state['installs'].items()):
        plugin, _, mp_name = key.partition('@')
        if args.marketplace and mp_name != args.marketplace:
            continue
        mp_dir = marketplace_path(mp_name)
        if not mp_dir.exists():
            continue
        plugins = marketplace_plugins(mp_dir)
        if plugin not in plugins:
            print(f'[warn] {key}: plugin no longer in marketplace, leaving install as-is')
            continue
        for tkey, tinfo in list(entry['targets'].items()):
            install_plugin(state, plugin, mp_name, plugins[plugin],
                           tinfo.get('project'), tinfo.get('copy', False),
                           tinfo.get('claude', True))
            print(f'[refresh] {key} @ {tkey}')


def cmd_status(args, state):
    print(f'state: {STATE_PATH}')
    for name in sorted(state['marketplaces']):
        dest = marketplace_path(name)
        head = '?'
        if dest.exists():
            try:
                head = run_git(['log', '-1', '--format=%h %ad %s', '--date=short'], cwd=dest)
            except RuntimeError:
                pass
        print(f'marketplace {name}: {state["marketplaces"][name]["url"]}\n  HEAD: {head}')
    for key, entry in sorted(state['installs'].items()):
        for tkey, tinfo in entry['targets'].items():
            v = tinfo.get('version')
            print(f'install {key} @ {tkey}'
                  + (f' v{v}' if v else '') + f' ({len(tinfo["files"])} files)')


def cmd_convert(args, state):
    out = translate_agent(args.file, args.to)
    if args.output:
        pathlib.Path(args.output).write_text(out)
        print(f'wrote {args.output}')
    else:
        sys.stdout.write(out)


def cmd_init_marketplace(args, state):
    root = pathlib.Path(args.path).resolve()
    name = args.name or root.name
    if (root / '.claude-plugin').exists():
        die(f'{root} already looks like a marketplace')
    example = 'example-plugin'
    (root / '.claude-plugin').mkdir(parents=True)
    (root / '.claude-plugin' / 'marketplace.json').write_text(json.dumps({
        'name': name,
        'owner': {'name': 'D4Science - gCube'},
        'plugins': [{'name': example, 'source': f'./plugins/{example}',
                     'description': 'Example plugin — rename or remove'}],
    }, indent=2) + '\n')
    pdir = root / 'plugins' / example
    (pdir / '.claude-plugin').mkdir(parents=True)
    (pdir / '.claude-plugin' / 'plugin.json').write_text(json.dumps({
        'name': example, 'version': '0.1.0',
        'description': 'Example plugin — rename or remove',
    }, indent=2) + '\n')
    (pdir / 'skills' / 'example-skill').mkdir(parents=True)
    (pdir / 'skills' / 'example-skill' / 'SKILL.md').write_text(
        '---\nname: example-skill\ndescription: Replace with a real skill.\n---\n\n'
        '# Example skill\n\nReplace me.\n')
    (pdir / 'agents').mkdir()
    (pdir / 'agents' / 'example-agent.md').write_text(
        '---\nname: example-agent\ndescription: Replace with a real agent.\n'
        'tools: Bash, Read, Edit, Write, Grep, Glob\n---\n\n'
        '# Example agent\n\nReplace me.\n')
    (pdir / 'commands').mkdir()
    (root / 'README.md').write_text(
        f'# {name} — agent/skill marketplace\n\n'
        '## Claude Code (native)\n\n'
        f'    claude plugin marketplace add <git-url>\n'
        f'    /plugin install {example}@{name}\n\n'
        '## Kilo Code and other tools (kilo-plugin-manager)\n\n'
        f'    plugin_manager.py add <git-url> --name {name}\n'
        f'    plugin_manager.py install {example}@{name} [--project <repo>]\n'
        f'    plugin_manager.py update\n')
    if not (root / '.git').exists():
        run_git(['init'], cwd=root)
    print(f'[scaffold] marketplace {name} created at {root}')


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    sub = ap.add_subparsers(dest='cmd', required=True)

    p = sub.add_parser('add', help='register + clone a marketplace git repo')
    p.add_argument('url')
    p.add_argument('--name')
    p.set_defaults(fn=cmd_add)

    p = sub.add_parser('remove', help='remove a marketplace checkout')
    p.add_argument('marketplace')
    p.add_argument('--force', action='store_true')
    p.set_defaults(fn=cmd_remove)

    p = sub.add_parser('list', help='list plugins in all marketplaces')
    p.add_argument('marketplace', nargs='?')
    p.set_defaults(fn=cmd_list)

    p = sub.add_parser('install', help='install a plugin (global or --project)')
    p.add_argument('plugin', help='plugin or plugin@marketplace')
    p.add_argument('--project', help='install into this repo instead of globally')
    p.add_argument('--copy', action='store_true',
                   help='copy skills instead of symlinking (survives marketplace removal)')
    p.add_argument('--no-claude', action='store_true',
                   help='skip .claude/agents and .claude/commands generation')
    p.set_defaults(fn=cmd_install)

    p = sub.add_parser('uninstall', help='remove an installed plugin')
    p.add_argument('plugin')
    p.add_argument('--project')
    p.set_defaults(fn=cmd_uninstall)

    p = sub.add_parser('update', help='git pull marketplaces + refresh installs')
    p.add_argument('marketplace', nargs='?')
    p.set_defaults(fn=cmd_update)

    p = sub.add_parser('status', help='show marketplaces and installs')
    p.set_defaults(fn=cmd_status)

    p = sub.add_parser('convert', help='translate one agent .md between formats')
    p.add_argument('file')
    p.add_argument('--to', choices=['kilo', 'claude'], required=True)
    p.add_argument('-o', '--output')
    p.set_defaults(fn=cmd_convert)

    p = sub.add_parser('init-marketplace', help='scaffold a new marketplace repo')
    p.add_argument('path')
    p.add_argument('--name')
    p.set_defaults(fn=cmd_init_marketplace)

    args = ap.parse_args()
    args.fn(args, load_state())


if __name__ == '__main__':
    main()
